### ISSUE TITLE
Text colours don’t meet accessibility contrast guidelines

### ISSUE THREAD

**Issue by lchski** [shawngraham/dhcu#1]
Hi! I was perusing your site (this looks like the repo for [dhcu.ca](https://dhcu.ca)). The course itself looks fascinating. Unfortunately the styles for both [the main body text](https://webaim.org/resources/contrastchecker/?fcolor=999999&bcolor=FFFFFF) and [the sidebar text](https://webaim.org/resources/contrastchecker/?fcolor=999999&bcolor=F4F4F4) don’t meet basic accessibility contrast guidelines. While this is a generally good thing to do, it seems especially pertinent as this is a somewhat university-affiliated site, and they definitely have accessibility compliance requirements.

Changing the text colour from `#999999` to something darker (`#525252` at the minimum, I think, though even further toward `#000000` is great) will bring you into compliance.

I’d make a PR, but this looks like the generated files as opposed to the source files.

Thanks for being so open with your work—it’s very interesting to follow along!

**Comment by shawngraham** [comment]
Hi @lchski - yep, it's a hugo generated site. Thanks for taking the time to look it over, and for the suggestions. I used hugo mostly because I'd never used it before... I'll dive into the template and see what I can sort out.

**Comment by lchski** [comment]
Cool—happy to help with it, too. If there’s a GitHub repo for the theme, might be worth duplicating this issue there, to push for accessibility improvements in it.

**Comment by shawngraham** [comment]
I found the relevant bit of the css, changed it up. Served locally, looked good, but when the site generated and I pushed it to the server, the darned css wouldn't upload- which says more about me & my webdev skills than I'd care to admit. Anyway, it's now #000000. Theme is at https://themes.gohugo.io/hugo-creative-portfolio-theme/

**Comment by shawngraham** [comment]
btw, thank you for the offer! I might take you up on that in a bit.
